language: node_js
notifications:
  email: false
node_js:
  - "8"
install: npm install && npm i -g npx
jobs:
  include:
    - stage: test
      script: npm test
    - stage: deploy
      script: bash ./scripts/.travis-deploy.sh
cache:
  directories:
    - node_modules
